// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-843qTTjWS8OhMPQ6uYSUvJ6mbhfgtwQ',
    appId: '1:1056760481900:web:4b7320b08a74207db07049',
    messagingSenderId: '1056760481900',
    projectId: 'medi-mart-16142',
    authDomain: 'medi-mart-16142.firebaseapp.com',
    storageBucket: 'medi-mart-16142.firebasestorage.app',
    measurementId: 'G-VK4GFGJPGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgIfgixYGZeAML1hQ1bonycKoEzTO-Fk',
    appId: '1:1056760481900:android:fb1f74400aa3d1a6b07049',
    messagingSenderId: '1056760481900',
    projectId: 'medi-mart-16142',
    storageBucket: 'medi-mart-16142.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxkQJSDS9hz2lfiR02jJDZuPk0RJFpr2c',
    appId: '1:1056760481900:ios:10e4fd2e56388222b07049',
    messagingSenderId: '1056760481900',
    projectId: 'medi-mart-16142',
    storageBucket: 'medi-mart-16142.firebasestorage.app',
    iosBundleId: 'com.example.mediMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxkQJSDS9hz2lfiR02jJDZuPk0RJFpr2c',
    appId: '1:1056760481900:ios:10e4fd2e56388222b07049',
    messagingSenderId: '1056760481900',
    projectId: 'medi-mart-16142',
    storageBucket: 'medi-mart-16142.firebasestorage.app',
    iosBundleId: 'com.example.mediMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-843qTTjWS8OhMPQ6uYSUvJ6mbhfgtwQ',
    appId: '1:1056760481900:web:5f9aeadcd5df639ab07049',
    messagingSenderId: '1056760481900',
    projectId: 'medi-mart-16142',
    authDomain: 'medi-mart-16142.firebaseapp.com',
    storageBucket: 'medi-mart-16142.firebasestorage.app',
    measurementId: 'G-18QHJ7B72K',
  );
}
